### ISSUE TITLE
One Player needs to be first person with a body mesh while the other needs to be third

### ISSUE THREAD

**Issue by KieranClarkee** [PlaceholderGames/2016-Team2Thirds#11]
We need one of the players who will be the one being hunted to have a visible body so that the hunter will be able to see it in game. Also the it needs to be in a first person perspective so that it would have an more immersive feeling in game which helps create a tense atmosphere.

**Comment by ShaunDavid1** [comment]
On the branch 'copyOfDash', I have added the first person view to the character in question. I'll continue to work on this to try and connect the camera to the head of the player so when the players head moves and sways, so will the camera. This will hopefully help create a more immersive and tense atmosphere.
