### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by Monofoot** [PlaceholderGames/2016-Team2Thirds#16]
The code for the minimap is finished but is on a local version on my laptop. I'm going to transfer the code over to the "TrapTests" commit because this will also give me access to four traps for me to create an action bar from. This issue will be updated as the minimap is further implemented.
(After meeting with the team, the complicated ping system cannot really be implemented until multiplayer and a second character is finished - this may take some time so will be illustrated in a separate issue.)

**Comment by KieranClarkee** [comment]
It may be a good idea to add images on the mini-map for the third person player's placed traps. This would help the player get a more clear understanding of how they are currently set up
