### ISSUE TITLE
Checklist - Draft #1

### ISSUE THREAD

**Issue by Monofoot** [PlaceholderGames/2016-Team2Thirds#18]
For our first release we have several issues we need to address before finally merging out first draft:

+ A quick merge (being done today, this will provide a platform for the team to see exactly where we are and any compatibility issues present)
+ We made a mistake in making our individual branches separate projects. This means I'll have to pull each branch one by one and make a big merge with them, and commit that as a new master. Once this is done, we can begin making progress at a much faster rate because we've identified why our Git is such a mess.

**Comment by Monofoot** [comment]
Update: Mistake is bigger than anticipated. Will all meet next self-study session to discuss alternatives and see if possibly we could rewrite our code, but use the master instead of our own separate projects. A hurdle; but we can make it work.

**Comment by Pagec531** [comment]
I wouldn't touch the branches it isn't all that bad i don't think its just a case of making sure that everyone's work that they do is firstly branched of the original master's work. So mine and shauns work is fine i know that as its all branched of the original.

**Comment by Pagec531** [comment]
If you want you could still work on the issues again just make sure they are all branched from the master.

**Comment by ShaunDavid1** [comment]
It's probably best to leave the merging stuff until Thursday when we can sit down with mike or tom and be sure everything is done properly.

**Comment by Pagec531** [comment]
I agree the most important thing will be the order of merging I think.  But if anyone has worked now on an issue that was a separate project I would say the best way around it would be to make a new branch that has branched of the newest master branch open up that unreal project located in the team2thirds folder that gets downloaded and then work on that one just re add the stuff you have already made on to that one.

**Comment by Pagec531** [comment]
Update after thursday meeting: 

Rob - copy new repo then chekout on to PlayerPlacedObjects make your changes and then add . --- commit -m "message" -- push origin -u PlayerPlacedObjects

Connor -- Sort the updating on multiplayer
