### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by ShaunDavid1** [PlaceholderGames/2016-Team2Thirds#22]
We'll need a splash screen ready for the demo so I'll make a start on that if that's cool with everyone?

**Comment by Pagec531** [comment]
Yeah that sounds great!

**Comment by ShaunDavid1** [comment]
A very basic splash screen is now in place, showing 'Team 2Thirds' and a placeholder for the title of the game. The splash screen then fades from black to the player. I'll leave this issue open for now as I can still improve on this later down the line.

**Comment by Monofoot** [comment]
An even BETTER splash screen is now in place
