### ISSUE TITLE
Name and Logo

### ISSUE THREAD

**Issue by ShaunDavid1** [PlaceholderGames/2016-Team2Thirds#23]
Real icing sort of stuff but we're going to need a name for the game, I thought if anyone has any ideas we could pop them in the comments on this issue? We'll probably need some a logo of sorts too.

**Comment by Pagec531** [comment]
Has anyone here watched Stranger Things I thought the style of the logo on that would be a good fit especially for the retro theme.

**Comment by ShaunDavid1** [comment]
Big fan of that idea, didn't you find some sort of camera effect a few months back that could add a distorted look? I think that could look pretty good on whatever name we come up with, help the title fit the theme even more.

**Comment by Pagec531** [comment]
Yea I did definitely could try and fit that in good idea.

**Comment by Pagec531** [comment]
![photofunia-1494102059](https://cloud.githubusercontent.com/assets/22525957/25776295/5fcdbff4-32b2-11e7-8682-9441d8db8433.jpg)

**Comment by Pagec531** [comment]
I made it on this site : https://m.photofunia.com/effects/retro-wave

**Comment by Pagec531** [comment]
If everyone is ok with this shall i add it to the main menu?

**Comment by ShaunDavid1** [comment]
Yeah we'll use this for the final build.

**Comment by ShaunDavid1** [comment]
Now that image is implemented into the game I'll close this issue, I've used the idea of a distorted camera effect on the bad guy camera, giving him a more alien feel.
