### ISSUE TITLE
First Person Camera

### ISSUE THREAD

**Issue by Monofoot** [PlaceholderGames/2016-Team2Thirds#26]
Camera for the first person has been vandalized!!! 
The first person character is now third person, and the camera is in an awkward spot behind his legs. This character needs to be changed back to the first person character and must be renamed from third person to first person - it's super confusing.

**Comment by ShaunDavid1** [comment]
That's probably my fault I was messing about with some stuff with the camera after I had initially made the character first person and must have merged the extra bits by mistake, I'll fix it.

**Comment by ShaunDavid1** [comment]
Camera is now fixed for the first person character.
