### ISSUE TITLE
First Demo Check List

### ISSUE THREAD

**Issue by Pagec531** [PlaceholderGames/2016-Team2Thirds#28]
- Splash Screen (Shaun)
- Start Game Menu (Kieran)
- Start Game Setup 1. Players get chosen (Connor)
                                2. Players placed in starting positions. (Connor)
                                3. Start game timer / end game timer - bad guy moves fast to place traps then moves                  slower after.(Shaun)
                                4. Maps 3 of them (Everyone)
                                5. End game for both players  (Rob)

All jobs are rough ideas and can change and the assignee's just a quick mock up we did to get demo done.

**Comment by ShaunDavid1** [comment]
We have achieved what we wanted to do for each of these.
