### ISSUE TITLE
BaseMap

### ISSUE THREAD

**Issue by Pagec531** [PlaceholderGames/2016-Team2Thirds#29]
Currently working on the basic map layout.

**Comment by ShaunDavid1** [comment]
I'm also currently working on a few ideas for the maps, mainly looking at lighting and how it can create a tense environment.

**Comment by ShaunDavid1** [comment]
I've built a basic map using the landscaping tools. Using mountains, I've split the map up into lanes and various sublanes, with an empty riverbed running width ways roughly 3/4 of the way through the map. I've duplicated this map into 2 other maps, so we currently have 3 identical map bases on the branch 'mapBuild'. I feel like we need to get together at the start of next week to make sure we're all on the same page with how we want to progress.

**Comment by ShaunDavid1** [comment]
The map is now up on the master and ready for stuff to be added to them, I'm working on the grass version of the map at the moment so if anyone wants to start filling out either of the other two they're both free. On my own branch I've added a fog that gives a darker feel to the map which applies two all three areas.
