### ISSUE TITLE
Possible problem with time travel mechanic

### ISSUE THREAD

**Issue by KieranClarkee** [PlaceholderGames/2016-Team2Thirds#37]
This issue is in relation to the updates to the teleport mechanic within the game.

We recently changed the game so that both players could teleport within the game by pressing a button. However another recent change that I believe may be a mistake is that the players now reset to their starting positions on the new map instead of the first idea of moving the character over to the new map at the same location.

An issue that I think this has created is that the idea was that the player would use the time travel ability to get past possible obstacles within the game.
For example:
The player comes across a river which is too deep and too fast flowing for the player to swim across, so the player has two options. Go back, or forward in time to overcome the obstacle. Going back may go to a time where the river is frozen and going forward could go to a time where the river has turned to lava. So this meant that the player had to make the correct decision to get past it.

However with the new idea of spawning the player back at the starting point, it could ruin the point of this mechanic. In the above scenario the player might as well swap to the frozen time zone as soon as they enter the game to get past that obstacle. Even then, if the player comes across another obstacle and time travels (Going back to the spawn point) the player would have the same issue that they have just overcome with the river.

**Comment by Pagec531** [comment]
I can always just stick to the original approach if that's what everyone wants but it will mean that the maps will have to be stacked rather than side by side. If everyone is okay with that let me know and i can get that done then test the teleport with it.
