### ISSUE TITLE
Map too large - workaround

### ISSUE THREAD

**Issue by Monofoot** [PlaceholderGames/2016-Team2Thirds#56]
Map is far too big to commit. Been unable to push for days because of this, only just got around the issue. Github recommends downloading an extension: https://git-lfs.github.com/
I'm going to test it right now with Kieran, and if it works then we'll need this extension to make any more commits.

**Comment by ShaunDavid1** [comment]
With the game functioning and only 'icing' changes left to be made, we'll all work off the same computer and create the executable on the local version of 'master', as the file for the map exceeds github's 100MB limit.
