### ISSUE TITLE
Presentation and Pitch

### ISSUE THREAD

**Issue by Monofoot** [PlaceholderGames/2016-Team2Thirds#59]
Both the presentation and pitch have been finished, please find them attached. We can discuss keynotes on Facebook or in the morning, though the majority of the presentations are now finished. 
[Displaced - Pitch.pptx](https://github.com/PlaceholderGames/Team2Thirds/files/987329/Displaced.-.Pitch.pptx)
[Team2Thirds Presentation.pptx](https://github.com/PlaceholderGames/Team2Thirds/files/987330/Team2Thirds.Presentation.pptx)

**Comment by ShaunDavid1** [comment]
Good job ladies.
